### ISSUE TITLE
Bump to new versions

### ISSUE THREAD

**Issue by eliegaboriau** [PopulateTools/decidim-module-anonymous_proposals#8]
Hello,
We might be interested in using this module with Decidim instances in 0.26 and maybe higher.
Do you plan to bump it or is not maintained anymore ?
Do you want to add it to Decidim ICE ?
Thanks

**Comment by ferblape** [comment]
Hi @eliegaboriau we are not planning a bump right now because we are quite busy with the redesign of Decidim.

A bump to 0.26 should be quick so we'll be happy to accept a PR and merge it. 

Once we have complete the redesign we need to catchup with this and other Decidim modules, make them compatible with 0.27 and 0.28 and maybe consider moving them to the community DICE repo.

**Comment by larsUE** [comment]
We can supply a PR of our version running on V0.27 in Zürich. @carlobeltrame or @Kagemaru could you do this?
